api_platform:

    # The title of the API.
    title: '%env(PROJECT_NAME)%'

    # The description of the API.
    description: 'An API for building ready-made calendars.'

    # The version of the API.
    version: '%env(VERSION_APP)%'

    # Set this to false if you want Webby to disappear.
    show_webby: true

    # Enable the entrypoint.
    enable_entrypoint: true

    # Enable the docs.
    enable_docs: true

    # Set mapping paths
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # Set patch formats
    patch_formats:
        json: ['application/merge-patch+json']

    # Set swagger version
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    # Set defaults
    defaults:
        pagination_maximum_items_per_page: 100
        pagination_items_per_page: 100
        pagination_client_items_per_page: true

    # Set collection
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage

    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Validation exception
        ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
