doctrine:
    dbal:
        dbname: "%env(resolve:DOCTRINE_DB_NAME)%"
        host: "%env(resolve:DOCTRINE_DB_HOST)%"
        port: "%env(resolve:DOCTRINE_DB_PORT)%"
        user: "%env(resolve:DOCTRINE_DB_USER)%"
        password: "%env(resolve:DOCTRINE_DB_PASS)%"
        driver: "%env(resolve:DOCTRINE_DB_DRIVER)%"
        server_version: "%env(resolve:DOCTRINE_DB_VERSION)%"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
