# ===========================================
# A development stack recipe to deliver the app via Nginx, PHP 8.0.x and MySQL 5.7.35.
#
# @author Björn Hempel <bjoern@hempel.de>
# @version 1.0 (2022-03-14)
# ===========================================

# ===========================================
# This file is used in combination with the docker-compose.yml file. For commands and usage see this file.
#
# Start app:
# ----------
# ❯ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# ===========================================

# Use docker compose version 3.8
version: "3.8"

# configure services
services:

  # Nginx to serve the app.
  nginx:
    ports:
      - ${NGINX_EXPOSE_PORT}:80

  # MySQL server
  db:
    ports:
      - ${MYSQL_EXPOSE_PORT}:${MYSQL_SERVER_PORT}

  # MySQL server
  db-test:
    ports:
      - ${MYSQL_EXPOSE_PORT_TEST}:${MYSQL_SERVER_PORT}
