# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api.base_url: '%env(resolve:API_BASE_URL)%'
    jwt.role: '%env(resolve:JWT_ROLE)%'
    backend.title.login: 'API Backend Login'
    backend.title.main: 'API Backend'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    App\OpenApi\VersionDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    App\Controller\VersionController:
        arguments: [ '@kernel' ]
        public: true

    App\EventListener\AddPaginationHeaders:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\Field\Configurator\CollectionCalendarImageConfigurator:
        tags:
            - { name: 'ea.field_configurator', priority: -1 }

    App\Field\Configurator\ImageEmptyConfigurator:
        arguments: [ '%kernel.project_dir%' ]

    App\Form\Type\FileUploadEmptyType:
        arguments: [ '%kernel.project_dir%' ]

    App\EventListener\Entity\UserListener:
        tags:
            - { name: 'doctrine.orm.entity_listener' }

    App\EventListener\Entity\HolidayListener:
        tags:
            - { name: 'doctrine.orm.entity_listener' }

    App\Service\CalendarBuilderService:
        arguments: [ '@kernel' ]

    App\Utils\Version\Version:
        arguments:
            - '%kernel.project_dir%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
